force-app/main/default/objects/Pokemon__c/Pokemon__c.object-meta.xml
<CustomObject>
    <label>Pokėmon</label>
    <nameField>
        <label>Pokėmon Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokėmon</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pokemon__c/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <label>Id</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Fire</fullName>
            </value>
            <value>
                <fullName>Water</fullName>
            </value>
            <value>
                <fullName>Grass</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Ice</fullName>
            </value>
            <value>
                <fullName>Fighting</fullName>
            </value>
            <value>
                <fullName>Poison</fullName>
            </value>
            <value>
                <fullName>Ground</fullName>
            </value>
            <value>
                <fullName>Flying</fullName>
            </value>
            <value>
                <fullName>Psychic</fullName>
            </value>
            <value>
                <fullName>Bug</fullName>
            </value>
            <value>
                <fullName>Rock</fullName>
            </value>
            <value>
                <fullName>Ghost</fullName>
            </value>
            <value>
                <fullName>Dark</fullName>
            </value>
            <value>
                <fullName>Dragon</fullName>
            </value>
            <value>
                <fullName>Steel</fullName>
            </value>
            <value>
                <fullName>Fairy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PokemonRetriever.cls
public class PokemonRetriever {
    
    public static void getPokemon() {
    	Http http = new Http();
        HttpRequest hr = new HttpRequest();
		hr.setEndpoint('https://pokeapi.co/api/v2/pokemon?limit=21&offset=130');
        hr.setMethod('GET');
        HttpResponse response = http.send(hr);
        
        if(response.getStatusCode() == 200) {
            Map<String, Object> resultMap = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
            List<Object> pokemons = (List<Object>) resultMap.get('results');
            
            List<Pokemon__c> pokemonList = new List<Pokemon__c>();
            for(Object pokemon: pokemons) {
                Map<String, Object> newPokemon = (Map<String, Object>) pokemon;
                pokemonList.add(GetPokemonDetails((String) newPokemon.get('url')));
            }
            insert pokemonList;
        }
    }
    
    public static Pokemon__c GetPokemonDetails(String url) {
        Http http = new Http();
        HttpRequest hr = new HttpRequest();
        hr.setEndpoint(url);
        hr.setMethod('GET');
        HttpResponse response = http.send(hr);
        Pokemon__c newPokemon = new Pokemon__c();
        
        if(response.getStatusCode() == 200) {
            String picklistValues = '';
            Map<String, Object> pokemon = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
            newPokemon.name = (String) pokemon.get('name');
            newPokemon.Id__c = (Integer) pokemon.get('id');
            Map<String, Object> sprites = (Map<String, Object>) pokemon.get('sprites');
            newPokemon.Image_URL__c = (String) sprites.get('front_shiny');
            
            List<Object> typeList = (List<Object>) pokemon.get('types');
            for(Object type: typeList) {
                Map<String, Object> t = (Map<String, Object>) type;
                Map<String, Object> actualTypes = (Map<String, Object>) t.get('type');
                picklistValues += (String) actualTypes.get('name') + ';';
            }
            
            newPokemon.Type__c = picklistValues.removeEnd(';');
        }
        return newPokemon;
    }
}